import { type EditorPage, type EditorElement } from './storage';

export function createIDEF0Template(): EditorPage {
  const elements: EditorElement[] = [
    // Основной блок функции
    {
      id: 'idef0_main',
      type: 'idef0-box',
      x: 400,
      y: 300,
      width: 200,
      height: 120,
      text: 'Функция',
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 1,
    },
    // Входы (слева)
    {
      id: 'idef0_input1',
      type: 'rectangle',
      x: 200,
      y: 320,
      width: 80,
      height: 30,
      text: 'Вход 1',
      fill: '#e3f2fd',
      stroke: '#1976d2',
      strokeWidth: 1,
      fontSize: 12,
      zIndex: 0,
    },
    {
      id: 'idef0_input2',
      type: 'rectangle',
      x: 200,
      y: 370,
      width: 80,
      height: 30,
      text: 'Вход 2',
      fill: '#e3f2fd',
      stroke: '#1976d2',
      strokeWidth: 1,
      fontSize: 12,
      zIndex: 0,
    },
    // Выходы (справа)
    {
      id: 'idef0_output1',
      type: 'rectangle',
      x: 720,
      y: 320,
      width: 80,
      height: 30,
      text: 'Выход 1',
      fill: '#fff3e0',
      stroke: '#f57c00',
      strokeWidth: 1,
      fontSize: 12,
      zIndex: 0,
    },
    // Управление (сверху)
    {
      id: 'idef0_control1',
      type: 'rectangle',
      x: 380,
      y: 200,
      width: 100,
      height: 30,
      text: 'Управление',
      fill: '#f3e5f5',
      stroke: '#7b1fa2',
      strokeWidth: 1,
      fontSize: 12,
      zIndex: 0,
    },
    // Механизм (снизу)
    {
      id: 'idef0_mechanism1',
      type: 'rectangle',
      x: 380,
      y: 480,
      width: 100,
      height: 30,
      text: 'Механизм',
      fill: '#e8f5e9',
      stroke: '#388e3c',
      strokeWidth: 1,
      fontSize: 12,
      zIndex: 0,
    },
    // Стрелки
    {
      id: 'idef0_arrow1',
      type: 'arrow',
      x: 280,
      y: 335,
      width: 120,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
    {
      id: 'idef0_arrow2',
      type: 'arrow',
      x: 600,
      y: 335,
      width: 120,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
  ];

  return {
    id: `page_${Date.now()}`,
    name: 'IDEF0 Диаграмма',
    elements,
    width: 1920,
    height: 1080,
    background: '#ffffff',
  };
}

export function createDFDTemplate(): EditorPage {
  const elements: EditorElement[] = [
    // Процесс
    {
      id: 'dfd_process1',
      type: 'dfd-process',
      x: 400,
      y: 300,
      width: 120,
      height: 80,
      text: 'Процесс 1',
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      fontSize: 14,
      zIndex: 1,
    },
    // Хранилище данных
    {
      id: 'dfd_store1',
      type: 'dfd-data-store',
      x: 200,
      y: 500,
      width: 100,
      height: 60,
      text: 'Хранилище',
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      fontSize: 12,
      zIndex: 1,
    },
    // Внешняя сущность
    {
      id: 'dfd_external1',
      type: 'dfd-external',
      x: 600,
      y: 300,
      width: 100,
      height: 60,
      text: 'Внешняя сущность',
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      fontSize: 12,
      zIndex: 1,
    },
    // Потоки данных
    {
      id: 'dfd_flow1',
      type: 'line',
      x: 300,
      y: 340,
      width: 100,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
    {
      id: 'dfd_flow2',
      type: 'line',
      x: 520,
      y: 340,
      width: 80,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
  ];

  return {
    id: `page_${Date.now()}`,
    name: 'DFD Диаграмма',
    elements,
    width: 1920,
    height: 1080,
    background: '#ffffff',
  };
}

export function createBPMNTemplate(): EditorPage {
  const elements: EditorElement[] = [
    // Стартовое событие
    {
      id: 'bpmn_start',
      type: 'bpmn-event',
      x: 200,
      y: 300,
      width: 40,
      height: 40,
      fill: '#4caf50',
      stroke: '#2e7d32',
      strokeWidth: 2,
      zIndex: 1,
    },
    // Задача
    {
      id: 'bpmn_task1',
      type: 'bpmn-task',
      x: 300,
      y: 290,
      width: 120,
      height: 60,
      text: 'Задача 1',
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      fontSize: 14,
      zIndex: 1,
    },
    // Шлюз
    {
      id: 'bpmn_gateway1',
      type: 'bpmn-gateway',
      x: 480,
      y: 300,
      width: 50,
      height: 50,
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 1,
    },
    // Еще одна задача
    {
      id: 'bpmn_task2',
      type: 'bpmn-task',
      x: 600,
      y: 290,
      width: 120,
      height: 60,
      text: 'Задача 2',
      fill: '#ffffff',
      stroke: '#000000',
      strokeWidth: 2,
      fontSize: 14,
      zIndex: 1,
    },
    // Конечное событие
    {
      id: 'bpmn_end',
      type: 'bpmn-event',
      x: 780,
      y: 300,
      width: 40,
      height: 40,
      fill: '#f44336',
      stroke: '#c62828',
      strokeWidth: 2,
      zIndex: 1,
    },
    // Потоки
    {
      id: 'bpmn_flow1',
      type: 'arrow',
      x: 240,
      y: 320,
      width: 60,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
    {
      id: 'bpmn_flow2',
      type: 'arrow',
      x: 420,
      y: 320,
      width: 60,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
    {
      id: 'bpmn_flow3',
      type: 'arrow',
      x: 530,
      y: 320,
      width: 70,
      height: 0,
      stroke: '#000000',
      strokeWidth: 2,
      zIndex: 0,
    },
  ];

  return {
    id: `page_${Date.now()}`,
    name: 'BPMN Диаграмма',
    elements,
    width: 1920,
    height: 1080,
    background: '#ffffff',
  };
}
