// Создаем контекст для управления языком интерфейса (русский/английский)
'use client';

import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Словари переводов
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Settings Modal
    'settings.title': 'Настройки',
    'settings.theme': 'Тема интерфейса',
    'settings.light': 'Светлая',
    'settings.dark': 'Тёмная',
    'settings.language': 'Язык интерфейса',
    
    // Profile Modal
    'profile.title': 'Мой профиль',
    'profile.photo': 'Фото профиля',
    'profile.photo.upload': 'Загрузите ваше фото. Рекомендуемый масштаб фото: 200x200. Максимальный размер фото: 5 МБ.',
    'profile.photo.change': 'Изменить фото',
    'profile.photo.uploadButton': 'Загрузить фото',
    'profile.photo.remove': 'Удалить',
    'profile.lastName': 'Фамилия',
    'profile.firstName': 'Имя',
    'profile.middleName': 'Отчество',
    'profile.birthDate': 'Дата рождения',
    'profile.email': 'Эл. почта',
    'profile.phone': 'Телефон',
    'profile.save': 'Сохранить изменения',
    'profile.logout': 'Выйти из аккаунта',
    
    // About Modal
    'about.title': 'О системе',
    'about.back': 'Назад',
    'about.privacy': 'Политика конфиденциальности',
    'about.version': 'Версия 1.0.0',
    'about.context': 'Context (рус. Контекст)',
    'about.description': 'Ответы на вопросы по загруженным документам, создание диаграмм по предметной области. Используя систему Context, вы соглашаетесь с',
    'about.privacyLink': 'Политикой конфиденциальности',
    'about.versionLabel': 'Версия',
    'about.support': 'Обратиться в поддержку',
    'about.support.email': 'Ваша электронная почта',
    'about.support.message': 'Ваше сообщение',
    'about.support.attach': 'Прикрепить файл',
    'about.support.send': 'Отправить',
    'about.support.placeholder.email': 'example@mail.com',
    'about.support.placeholder.message': 'Опишите вашу проблему или вопрос...',
    
    // Privacy Policy
    'privacy.section1.title': '1. Общие положения',
    'privacy.section1.text1': 'Настоящая Политика конфиденциальности определяет порядок обработки и защиты персональных данных пользователей сервиса Context (далее — «Сервис»). Используя Сервис, вы соглашаетесь с условиями настоящей Политики конфиденциальности.',
    'privacy.section1.text2': 'Администрация Сервиса обязуется соблюдать конфиденциальность персональных данных пользователей в соответствии с действующим законодательством.',
    'privacy.section2.title': '2. Собираемые данные',
    'privacy.section2.text1': 'При использовании Сервиса мы собираем следующую информацию:',
    'privacy.section2.item1': 'Электронный адрес (email) для идентификации пользователя',
    'privacy.section2.item2': 'Информация о проектах, созданных пользователем',
    'privacy.section2.item3': 'Загруженные пользователем файлы и документы',
    'privacy.section2.item4': 'Данные о взаимодействии с Сервисом (время использования, действия пользователя)',
    'privacy.section3.title': '3. Цели использования данных',
    'privacy.section3.text1': 'Собранные данные используются для следующих целей:',
    'privacy.section3.item1': 'Предоставление доступа к функциям Сервиса',
    'privacy.section3.item2': 'Идентификация и аутентификация пользователей',
    'privacy.section3.item3': 'Обработка и анализ загруженных файлов для ответов на вопросы',
    'privacy.section3.item4': 'Создание диаграмм на основе загруженных данных',
    'privacy.section3.item5': 'Улучшение качества работы Сервиса',
    'privacy.section3.item6': 'Обеспечение безопасности и предотвращение мошенничества',
    'privacy.section3.item7': 'Информирование пользователей об изменениях в Сервисе',
    'privacy.section4.title': '4. Защита персональных данных',
    'privacy.section4.text1': 'Администрация Сервиса принимает необходимые технические и организационные меры для защиты персональных данных от неправомерного доступа, уничтожения, изменения, блокирования, копирования, распространения, а также от иных неправомерных действий.',
    'privacy.section5.title': '5. Передача данных третьим лицам',
    'privacy.section5.text1': 'Администрация Сервиса не передает персональные данные третьим лицам, за исключением следующих случаев:',
    'privacy.section5.item1': 'Пользователь дал согласие на такие действия',
    'privacy.section5.item2': 'Передача предусмотрена законодательством в рамках установленной процедуры',
    'privacy.section5.item3': 'Передача необходима для работы Сервиса или его функций (например, обработка файлов с использованием внешних сервисов)',
    'privacy.section6.title': '6. Права пользователей',
    'privacy.section6.text1': 'Пользователь имеет право:',
    'privacy.section6.item1': 'Получать информацию о своих персональных данных, обрабатываемых Сервисом',
    'privacy.section6.item2': 'Требовать уточнения, блокирования или уничтожения персональных данных',
    'privacy.section6.item3': 'Удалить свой аккаунт и связанные с ним данные',
    'privacy.section6.text2': 'Для реализации своих прав пользователь может обратиться к Администрации Сервиса через форму обратной связи на странице «О системе».',
    'privacy.section7.title': '7. Использование Cookies',
    'privacy.section7.text1': 'Сервис использует технологию cookies для обеспечения удобства использования и улучшения функциональности.',
    'privacy.section7.text2': 'Пользователь может настроить свой браузер для отказа от cookies, однако это может ограничить доступ к некоторым функциям Сервиса.',
    'privacy.section8.title': '8. Изменения в Политике конфиденциальности',
    'privacy.section8.text1': 'Администрация Сервиса оставляет за собой право вносить изменения в настоящую Политику конфиденциальности. Актуальная версия всегда доступна на данной странице.',
    'privacy.section8.text2': 'При внесении существенных изменений пользователи будут уведомлены через Сервис или по электронной почте.',
    'privacy.section9.title': '9. Обратиться в поддержку',
    'privacy.section9.text1': 'По всем вопросам, связанным с обработкой персональных данных, вы можете обратиться к Администрации Сервиса через форму обратной связи на странице «О системе».',
    
    // Version Info
    'version.features.title': 'Основные возможности',
    'version.features.text1': 'CASE-средство Context позволяет быстро анализировать документы и создавать диаграммы по текстовому описанию. Возможности:',
    'version.features.item1': 'Загрузка документов различных форматов (PDF, DOCX и другие)',
    'version.features.item2': 'Анализ и выдача ответов на вопросы по загруженным документам',
    'version.features.item3': 'Создание и экспорт диаграмм различных типов (UML, ER и другие)',
    'version.features.item4': 'Создание глоссария и кода (PlantUML) диаграмм различных типов',
    'version.diagrams.title': 'Доступные типы диаграмм',
    'version.diagrams.text1': 'В текущей версии доступны следующие типы диаграмм:',
    'version.diagrams.item1': 'Семейство UML: Use Case, Sequence и другие (всего 8 типов)',
    'version.diagrams.item2': 'Диаграмма Ганта (Gantt)',
    'version.diagrams.item3': 'Диаграмма сущность-связь (Entity-Relationships)',
    'version.diagrams.item4': 'Интеллект-карта (MindMap)',
    'version.diagrams.item5': 'Диаграмма обмена данными (JSON)',
    'version.diagrams.item6': 'Иерархическая структура работ (WBS)',
    'version.formats.title': 'Поддерживаемые форматы документов',
    'version.formats.text1': 'Система поддерживает загрузку и обработку следующих типов файлов:',
    'version.formats.item1': 'PDF документы (.pdf)',
    'version.formats.item2': 'Документы Microsoft Word (.docx)',
    'version.formats.item3': 'Таблицы Microsoft Excel (.xlsx)',
    'version.formats.item4': 'Текстовые файлы (.txt)',
    'version.technical.title': 'Технические детали',
    'version.technical.text1': 'Система разработана с использованием:',
    'version.technical.item1': 'Библиотеки React для построения пользовательского интерфейса',
    'version.technical.item2': 'Фреймворка Next.js для создания веб-приложений',
    'version.technical.item3': 'Языка TypeScript для повышения надежности кода',
    'version.technical.item4': 'CSS-фреймворка Tailwind CSS для быстрой стилизации интерфейса',
    'version.technical.item5': 'Модели Mixtral 8x22B для анализа документов, генерации диаграмм',
    'version.technical.item6': 'API PlantUML для преобразования текстового описания в диаграммы',
    'version.technical.item7': 'Базы данных IndexedDB для хранения проектов и диаграмм в браузере',
    'version.technical.item8': 'Платформы Vercel для развертывания и хостинга веб-приложения',
    
    // Projects Page
    'projects.title': 'Проекты',
    'projects.description': 'Загружайте документы и получайте ответы на вопросы по ним',
    'projects.create': 'Создать проект',
    'projects.myProjects': 'Мои проекты',
    'projects.search': 'Поиск по названию...',
    'projects.sort.date': 'По дате создания',
    'projects.sort.alphabet': 'По алфавиту',
    'projects.empty.title': 'Проекты отсутствуют...',
    'projects.empty.description': 'Создайте свой первый проект, загрузите документы и получите ответы на вопросы по ним',
    'projects.table.name': 'Название',
    'projects.table.description': 'Краткое описание',
    'projects.table.date': 'Дата создания',
    'projects.edit': 'Редактировать',
    'projects.move': 'Перенести в папку',
    'projects.delete': 'Удалить',
    'projects.folder.create': 'Создание папки',
    'projects.folder.move': 'Перенести в папку',
    'projects.folder.name': 'Название папки',
    'projects.folder.back': 'Назад',
    'projects.folder.createButton': 'Создать папку',
    'projects.folder.createNew': 'Создать новую папку',
    'projects.folder.moveButton': 'Переместить',
    'projects.folder.empty': 'Папки отсутствуют',
    'projects.loading': 'Загрузка...',
    'common.loading': 'Загрузка...',
    
    // Diagrams Page
    'diagrams.title': 'Диаграммы',
    'diagrams.description': 'Получайте готовые диаграммы по текстовому описанию',
    'diagrams.selectType': 'Выбрать тип диаграммы',
    'diagrams.myDiagrams': 'Мои диаграммы',
    'diagrams.search': 'Поиск по названию...',
    'diagrams.sort.date': 'По дате создания',
    'diagrams.sort.alphabet': 'По алфавиту',
    'diagrams.empty.title': 'Диаграммы отсутствуют...',
    'diagrams.empty.description': 'Создайте свою первую диаграмму, выбрав ее тип и описав предметную область',
    'diagrams.table.name': 'Название',
    'diagrams.table.type': 'Тип диаграммы',
    'diagrams.table.date': 'Дата создания',
    'diagrams.edit': 'Редактировать',
    'diagrams.move': 'Перенести в папку',
    'diagrams.delete': 'Удалить',
    'diagrams.folder.create': 'Создание папки',
    'diagrams.folder.move': 'Перенести в папку',
    'diagrams.folder.name': 'Название папки',
    'diagrams.folder.back': 'Назад',
    'diagrams.folder.createButton': 'Создать папку',
    'diagrams.folder.createNew': 'Создать новую папку',
    'diagrams.folder.moveButton': 'Переместить',
    'diagrams.folder.empty': 'Папки отсутствуют',
    'diagrams.loading': 'Загрузка...',
    
    // Diagram Type Selection
    'diagrams.chat.selectType.filter.all': 'Все',
    'diagrams.chat.selectType.filter.standard': 'Стандарт или нотация',
    'diagrams.chat.selectType.filter.purpose': 'Цель использования',
    'diagrams.chat.selectType.filter.tag': 'Теги',
    'diagrams.chat.selectType.sort.alphabet': 'По алфавиту',
    'diagrams.chat.selectType.sort.popularity': 'По популярности',
    
    // Project Detail Page
    'project.documents': 'Документы',
    'project.dragFiles': 'Перетащите файлы сюда',
    'project.orClickButton': 'или нажмите кнопку ниже',
    'project.addDocuments': 'Добавить документы',
    'project.uploadDocuments': 'Загрузите документы, чтобы начать работу с ними',
    'project.enterMessage': 'Введите сообщение...',
    'project.loading': 'Загрузка...',
    'project.pleaseUpload': 'Пожалуйста, сначала загрузите документы для анализа.',
    'project.errorProcessing': 'Ошибка при обработке запроса:',
    'project.failedToGetAnswer': 'Не удалось получить ответ.',
    'project.unknownError': 'Неизвестная ошибка',
    'project.uploadedProcessed': 'Загружено и обработано документов:',
    'project.of': 'из',
    'project.back': 'Назад',
    'project.edit.title': 'Редактирование проекта',
    'project.edit.subtitle': 'Измените информацию о проекте',
    'project.edit.requiredFields': '* - обязательные поля',
    'project.edit.name': 'Название проекта',
    'project.edit.namePlaceholder': 'Введите название проекта...',
    'project.edit.description': 'Краткое описание проекта',
    'project.edit.descriptionPlaceholder': 'Введите описание проекта...',
    'project.edit.cancel': 'Отмена',
    'project.edit.save': 'Сохранить',
    'project.edit.saving': 'Сохранение...',
    
    // Diagram Detail Page
    'diagram.type': 'Тип диаграммы',
    'diagram.selectType': 'Выберите тип диаграммы',
    'diagram.search': 'Поиск',
    'diagram.sort': 'Сортировка',
    'diagram.filters': 'Фильтры',
    'diagram.notFound': 'Не нашли нужный тип?',
    'diagram.notFoundDescription': 'В ближайшее время будут добавлены новые типы, следите за обновлениями в разделе',
    'diagram.aboutSystem': 'о системе',
    'diagram.describeSubject': 'Опишите предметную область и конкретный объект, диаграмму которого нужно будет построить',
    'diagram.enterName': 'Введите название объекта или процесса для диаграммы...',
    'diagram.describeArea': 'Опишите предметную область и конкретный объект...',
    'diagram.selectTypeFirst': 'Сначала выберите тип диаграммы...',
    'diagram.describeManually': 'Опишите предметную область вручную',
    'diagram.back': 'Назад',
    'diagram.searchPlaceholder': 'Введите название или описание диаграммы',
    'diagram.removeFilters': 'Убрать фильтры',
    'diagram.creationMethod': 'Способ создания диаграммы',
    'diagram.selectCreationMethod': 'Выберите способ создания диаграммы',
    'diagram.fromProjects': 'Выбрать из моих проектов',
    'diagram.fromProjectsDescription': 'Использовать данные из существующего проекта',
    'diagram.fromScratch': 'Создать с нуля',
    'diagram.selectProjectButton': 'Выбрать проект',
    'diagram.enterData': 'Ввести данные',
    'diagram.selectProject': 'Выберите проект',
    'diagram.projectTable.name': 'Название',
    'diagram.projectTable.description': 'Краткое описание',
    'diagram.projectTable.date': 'Дата создания',
    'diagram.documentsProcessed': 'Обработаны документы:',
    'diagram.nowSelectObject': 'Теперь можно выбрать объект, по которому будет построена диаграмма.',
    'diagram.processingRequest': 'Обработка запроса',
    'diagram.definingRequirements': 'Определение требований',
    'diagram.generatingCode': 'Формирование кода',
    'diagram.creatingDiagram': 'Создание диаграммы',
    'diagram.reportError': 'Сообщить об ошибке',
    'diagram.diagram': 'Диаграмма',
    'diagram.code': 'Код',
    'diagram.downloadPNG': 'Скачать PNG',
    'diagram.copyCode': 'Скопировать код',
    'diagram.codeCopied': 'Код скопирован в буфер обмена',
    'diagram.glossaryTitle': 'Глоссарий элементов диаграммы',
    'diagram.element': 'Элемент',
    'diagram.description': 'Описание',
    'diagram.contactSupport': 'Обратиться в поддержку',
    'diagram.yourEmail': 'Ваша электронная почта',
    'diagram.send': 'Отправить',
    
    // Layout (Sidebar)
    'sidebar.projects': 'Проекты',
    'sidebar.diagrams': 'Диаграммы',
    'sidebar.settings': 'Настройки',
    'sidebar.about': 'О системе',
  },
  en: {
    // Settings Modal
    'settings.title': 'Settings',
    'settings.theme': 'Interface Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Interface Language',
    
    // Profile Modal
    'profile.title': 'My Profile',
    'profile.photo': 'Profile Photo',
    'profile.photo.upload': 'Upload your photo. Recommended photo scale: 200x200. Maximum photo size: 5 MB.',
    'profile.photo.change': 'Change Photo',
    'profile.photo.uploadButton': 'Upload Photo',
    'profile.photo.remove': 'Remove',
    'profile.lastName': 'Last Name',
    'profile.firstName': 'First Name',
    'profile.middleName': 'Middle Name',
    'profile.birthDate': 'Date of Birth',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.save': 'Save Changes',
    'profile.logout': 'Sign Out',
    
    // About Modal
    'about.title': 'About the System',
    'about.back': 'Back',
    'about.privacy': 'Privacy Policy',
    'about.version': 'Version 1.0.0',
    'about.context': 'Context',
    'about.description': 'Answers to questions about uploaded documents, creating diagrams for the subject area. By using the Context system, you agree to the',
    'about.privacyLink': 'Privacy Policy',
    'about.versionLabel': 'Version',
    'about.support': 'Contact Support',
    'about.support.email': 'Your Email',
    'about.support.message': 'Your Message',
    'about.support.attach': 'Attach File',
    'about.support.send': 'Send',
    'about.support.placeholder.email': 'example@mail.com',
    'about.support.placeholder.message': 'Describe your problem or question...',
    
    // Privacy Policy
    'privacy.section1.title': '1. General Provisions',
    'privacy.section1.text1': 'This Privacy Policy defines the procedure for processing and protecting personal data of users of the Context service (hereinafter - "Service"). By using the Service, you agree to the terms of this Privacy Policy.',
    'privacy.section1.text2': 'The Service Administration undertakes to observe the confidentiality of users\' personal data in accordance with applicable law.',
    'privacy.section2.title': '2. Data Collected',
    'privacy.section2.text1': 'When using the Service, we collect the following information:',
    'privacy.section2.item1': 'Email address for user identification',
    'privacy.section2.item2': 'Information about projects created by the user',
    'privacy.section2.item3': 'Files and documents uploaded by the user',
    'privacy.section2.item4': 'Data on interaction with the Service (usage time, user actions)',
    'privacy.section3.title': '3. Purpose of Data Use',
    'privacy.section3.text1': 'The collected data is used for the following purposes:',
    'privacy.section3.item1': 'Providing access to Service functions',
    'privacy.section3.item2': 'User identification and authentication',
    'privacy.section3.item3': 'Processing and analyzing uploaded files to answer questions',
    'privacy.section3.item4': 'Creating diagrams based on uploaded data',
    'privacy.section3.item5': 'Improving the quality of the Service',
    'privacy.section3.item6': 'Ensuring security and preventing fraud',
    'privacy.section3.item7': 'Informing users about changes in the Service',
    'privacy.section4.title': '4. Personal Data Protection',
    'privacy.section4.text1': 'The Service Administration takes necessary technical and organizational measures to protect personal data from unauthorized access, destruction, alteration, blocking, copying, distribution, as well as from other unlawful actions.',
    'privacy.section5.title': '5. Data Transfer to Third Parties',
    'privacy.section5.text1': 'The Service Administration does not transfer personal data to third parties, except in the following cases:',
    'privacy.section5.item1': 'The user has given consent to such actions',
    'privacy.section5.item2': 'Transfer is provided for by law within the established procedure',
    'privacy.section5.item3': 'Transfer is necessary for the operation of the Service or its functions (e.g., file processing using external services)',
    'privacy.section6.title': '6. User Rights',
    'privacy.section6.text1': 'The user has the right to:',
    'privacy.section6.item1': 'Receive information about their personal data processed by the Service',
    'privacy.section6.item2': 'Demand clarification, blocking, or destruction of personal data',
    'privacy.section6.item3': 'Delete their account and associated data',
    'privacy.section6.text2': 'To exercise their rights, the user can contact the Service Administration through the feedback form on the "About System" page.',
    'privacy.section7.title': '7. Use of Cookies',
    'privacy.section7.text1': 'The Service uses cookie technology to ensure ease of use and improve functionality.',
    'privacy.section7.text2': 'The user can configure their browser to refuse cookies, but this may limit access to some Service functions.',
    'privacy.section8.title': '8. Changes to Privacy Policy',
    'privacy.section8.text1': 'The Service Administration reserves the right to make changes to this Privacy Policy. The current version is always available on this page.',
    'privacy.section8.text2': 'When significant changes are made, users will be notified through the Service or by email.',
    'privacy.section9.title': '9. Contact Support',
    'privacy.section9.text1': 'For all questions related to the processing of personal data, you can contact the Service Administration through the feedback form on the "About System" page.',
    
    // Version Info
    'version.features.title': 'Main Features',
    'version.features.text1': 'The Context CASE tool allows you to quickly analyze documents and create diagrams from text descriptions. Features:',
    'version.features.item1': 'Uploading documents in various formats (PDF, DOCX, and others)',
    'version.features.item2': 'Analysis and answering questions based on uploaded documents',
    'version.features.item3': 'Creation and export of various diagram types (UML, ER, and others)',
    'version.features.item4': 'Creation of glossary and code (PlantUML) for various diagram types',
    'version.diagrams.title': 'Available Diagram Types',
    'version.diagrams.text1': 'The current version supports the following diagram types:',
    'version.diagrams.item1': 'UML family: Use Case, Sequence, and others (8 types in total)',
    'version.diagrams.item2': 'Gantt Chart',
    'version.diagrams.item3': 'Entity-Relationship Diagram',
    'version.diagrams.item4': 'MindMap',
    'version.diagrams.item5': 'JSON Data Exchange Diagram',
    'version.diagrams.item6': 'Work Breakdown Structure (WBS)',
    'version.formats.title': 'Supported Document Formats',
    'version.formats.text1': 'The system supports uploading and processing the following file types:',
    'version.formats.item1': 'PDF documents (.pdf)',
    'version.formats.item2': 'Microsoft Word documents (.docx)',
    'version.formats.item3': 'Microsoft Excel spreadsheets (.xlsx)',
    'version.formats.item4': 'Text files (.txt)',
    'version.technical.title': 'Technical Details',
    'version.technical.text1': 'The system is developed using:',
    'version.technical.item1': 'React library for building the user interface',
    'version.technical.item2': 'Next.js framework for building web applications',
    'version.technical.item3': 'TypeScript language for increased code reliability',
    'version.technical.item4': 'Tailwind CSS framework for rapid interface styling',
    'version.technical.item5': 'Mixtral 8x22B model for document analysis, diagram generation',
    'version.technical.item6': 'PlantUML API for converting text descriptions into diagrams',
    'version.technical.item7': 'IndexedDB database for storing projects and diagrams in the browser',
    'version.technical.item8': 'Vercel platform for deploying and hosting the web application',
    
    // Projects Page
    'projects.title': 'Projects',
    'projects.description': 'Upload documents and get answers to questions about them',
    'projects.create': 'Create Project',
    'projects.myProjects': 'My Projects',
    'projects.search': 'Search by name...',
    'projects.sort.date': 'By Creation Date',
    'projects.sort.alphabet': 'Alphabetically',
    'projects.empty.title': 'No Projects...',
    'projects.empty.description': 'Create your first project, upload documents and get answers to questions about them',
    'projects.table.name': 'Name',
    'projects.table.description': 'Short Description',
    'projects.table.date': 'Creation Date',
    'projects.edit': 'Edit',
    'projects.move': 'Move to Folder',
    'projects.delete': 'Delete',
    'projects.folder.create': 'Create Folder',
    'projects.folder.move': 'Move to Folder',
    'projects.folder.name': 'Folder Name',
    'projects.folder.back': 'Back',
    'projects.folder.createButton': 'Create Folder',
    'projects.folder.createNew': 'Create New Folder',
    'projects.folder.moveButton': 'Move',
    'projects.folder.empty': 'No Folders',
    'projects.loading': 'Loading...',
    
    // Diagrams Page
    'diagrams.title': 'Diagrams',
    'diagrams.description': 'Get ready-made diagrams from text descriptions',
    'diagrams.selectType': 'Select Diagram Type',
    'diagrams.myDiagrams': 'My Diagrams',
    'diagrams.search': 'Search by name...',
    'diagrams.sort.date': 'By Creation Date',
    'diagrams.sort.alphabet': 'Alphabetically',
    'diagrams.empty.title': 'No Diagrams...',
    'diagrams.empty.description': 'Create your first diagram by selecting its type and describing the subject area',
    'diagrams.table.name': 'Name',
    'diagrams.table.type': 'Diagram Type',
    'diagrams.table.date': 'Creation Date',
    'diagrams.edit': 'Edit',
    'diagrams.move': 'Move to Folder',
    'diagrams.delete': 'Delete',
    'diagrams.folder.create': 'Create Folder',
    'diagrams.folder.move': 'Move to Folder',
    'diagrams.folder.name': 'Folder Name',
    'diagrams.folder.back': 'Back',
    'diagrams.folder.createButton': 'Create Folder',
    'diagrams.folder.createNew': 'Create New Folder',
    'diagrams.folder.moveButton': 'Move',
    'diagrams.folder.empty': 'No Folders',
    'diagrams.loading': 'Loading...',
    'common.loading': 'Loading...',
    
    // Diagram Type Selection
    'diagrams.chat.selectType.filter.all': 'All',
    'diagrams.chat.selectType.filter.standard': 'Standard or Notation',
    'diagrams.chat.selectType.filter.purpose': 'Purpose',
    'diagrams.chat.selectType.filter.tag': 'Tags',
    'diagrams.chat.selectType.sort.alphabet': 'Alphabetically',
    'diagrams.chat.selectType.sort.popularity': 'By Popularity',
    
    // Project Detail Page
    'project.documents': 'Documents',
    'project.dragFiles': 'Drag files here',
    'project.orClickButton': 'or click the button below',
    'project.addDocuments': 'Add Documents',
    'project.uploadDocuments': 'Upload documents to start working with them',
    'project.enterMessage': 'Enter message...',
    'project.loading': 'Loading...',
    'project.pleaseUpload': 'Please upload documents first for analysis.',
    'project.errorProcessing': 'Error processing request:',
    'project.failedToGetAnswer': 'Failed to get answer.',
    'project.unknownError': 'Unknown error',
    'project.uploadedProcessed': 'Documents uploaded and processed:',
    'project.of': 'of',
    'project.back': 'Back',
    'project.edit.title': 'Edit Project',
    'project.edit.subtitle': 'Change project information',
    'project.edit.requiredFields': '* - required fields',
    'project.edit.name': 'Project Name',
    'project.edit.namePlaceholder': 'Enter project name...',
    'project.edit.description': 'Brief Description',
    'project.edit.descriptionPlaceholder': 'Enter project description...',
    'project.edit.cancel': 'Cancel',
    'project.edit.save': 'Save',
    'project.edit.saving': 'Saving...',
    
    // Diagram Detail Page
    'diagram.type': 'Diagram Type',
    'diagram.selectType': 'Select diagram type',
    'diagram.search': 'Search',
    'diagram.sort': 'Sort',
    'diagram.filters': 'Filters',
    'diagram.notFound': 'Didn\'t find the right type?',
    'diagram.notFoundDescription': 'New types will be added soon, follow updates in the section',
    'diagram.aboutSystem': 'about system',
    'diagram.describeSubject': 'Describe the subject area and the specific object for which a diagram needs to be built',
    'diagram.enterName': 'Enter the name of the object or process for the diagram...',
    'diagram.describeArea': 'Describe the subject area and the specific object...',
    'diagram.selectTypeFirst': 'First select a diagram type...',
    'diagram.describeManually': 'Describe the subject area manually',
    'diagram.back': 'Back',
    'diagram.searchPlaceholder': 'Enter diagram name or description',
    'diagram.removeFilters': 'Remove Filters',
    'diagram.creationMethod': 'Diagram Creation Method',
    'diagram.selectCreationMethod': 'Select a diagram creation method',
    'diagram.fromProjects': 'Select from my projects',
    'diagram.fromProjectsDescription': 'Use data from an existing project',
    'diagram.fromScratch': 'Create from scratch',
    'diagram.selectProjectButton': 'Select Project',
    'diagram.enterData': 'Enter Data',
    'diagram.selectProject': 'Select Project',
    'diagram.projectTable.name': 'Name',
    'diagram.projectTable.description': 'Brief Description',
    'diagram.projectTable.date': 'Creation Date',
    'diagram.documentsProcessed': 'Documents processed:',
    'diagram.nowSelectObject': 'Now you can select an object for which the diagram will be built.',
    'diagram.processingRequest': 'Processing Request',
    'diagram.definingRequirements': 'Defining Requirements',
    'diagram.generatingCode': 'Generating Code',
    'diagram.creatingDiagram': 'Creating Diagram',
    'diagram.reportError': 'Report an Error',
    'diagram.diagram': 'Diagram',
    'diagram.code': 'Code',
    'diagram.downloadPNG': 'Download PNG',
    'diagram.copyCode': 'Copy Code',
    'diagram.codeCopied': 'Code copied to clipboard',
    'diagram.glossaryTitle': 'Diagram Elements Glossary',
    'diagram.element': 'Element',
    'diagram.description': 'Description',
    'diagram.contactSupport': 'Contact Support',
    'diagram.yourEmail': 'Your Email',
    'diagram.send': 'Send',
    
    // Diagram Type Cards - Descriptions
    'diagram.type.Sequence.description': 'A sequence diagram displays the interaction of objects over time through message exchange between system participants and call sequences',
    'diagram.type.UseCase.description': 'A use case diagram describes functional requirements of a system through the interaction of actors and use cases with boundary indication',
    'diagram.type.Class.description': 'A class diagram shows the structure of a system through classes, their attributes, methods, and relationships, including inheritance and composition',
    'diagram.type.Object.description': 'An object diagram displays specific instances of classes and their relationships at a certain point in time during system execution with value indication',
    'diagram.type.Activity.description': 'An activity diagram models business processes and workflows, showing the sequence of actions, decision-making, and parallel flows',
    'diagram.type.Component.description': 'A component diagram shows the architecture of a system and its components, indicating interfaces, dependencies, and interaction methods',
    'diagram.type.Deployment.description': 'A deployment diagram displays the physical architecture of a system, showing the placement of components on deployment nodes and connections between them',
    'diagram.type.Statechart.description': 'A statechart diagram models the lifecycle of objects and their states, showing transitions between states, transition conditions, and actions',
    'diagram.type.Gantt.description': 'A Gantt chart visualizes project timelines and tasks, showing duration, dependencies, work sequence, and resources',
    'diagram.type.MindMap.description': 'A mind map presents ideas and concepts in a hierarchical structure, showing connections between concepts, their mutual arrangement, and grouping',
    'diagram.type.ER.description': 'An entity-relationship diagram models the structure of a database, showing entities, their attributes, and relationships with relationship type indication',
    'diagram.type.WBS.description': 'A work breakdown structure decomposes a project into tasks, showing the hierarchy of work, their interconnections in the project structure, and levels of detail',
    'diagram.type.JSON.description': 'A JSON diagram visualizes data structure in JSON format, showing objects, arrays, their nesting with data type and value indication',
    
    // Diagram Type Cards - Tags and Filters
    'diagram.tag.UML': 'UML',
    'diagram.tag.Взаимодействие': 'Interaction',
    'diagram.tag.Поведение': 'Behavior',
    'diagram.tag.Функции': 'Functions',
    'diagram.tag.Требования': 'Requirements',
    'diagram.tag.Структура': 'Structure',
    'diagram.tag.Классы': 'Classes',
    'diagram.tag.Объекты': 'Objects',
    'diagram.tag.Динамика': 'Dynamics',
    'diagram.tag.Архитектура': 'Architecture',
    'diagram.tag.Состояние': 'State',
    'diagram.tag.Время': 'Time',
    'diagram.tag.Проект': 'Project',
    'diagram.tag.Планирование': 'Planning',
    'diagram.tag.Иерархия': 'Hierarchy',
    'diagram.tag.Связи': 'Relationships',
    'diagram.tag.Базы данных': 'Databases',
    'diagram.tag.Данные': 'Data',
    'diagram.tag.Формат': 'Format',
    'diagram.standard.UML': 'UML',
    'diagram.standard.Управление проектами': 'Project Management',
    'diagram.standard.Идеи': 'Ideas',
    'diagram.standard.База данных': 'Database',
    'diagram.standard.Данные': 'Data',
    'diagram.purpose.Взаимодействие': 'Interaction',
    'diagram.purpose.Требования': 'Requirements',
    'diagram.purpose.Архитектура': 'Architecture',
    'diagram.purpose.Моделирование': 'Modeling',
    'diagram.purpose.Бизнес-процессы': 'Business Processes',
    'diagram.purpose.Моделирование состояний': 'State Modeling',
    'diagram.purpose.Управление проектами': 'Project Management',
    'diagram.purpose.Идеи': 'Ideas',
    'diagram.purpose.База данных': 'Database',
    
    // Layout (Sidebar)
    'sidebar.projects': 'Projects',
    'sidebar.diagrams': 'Diagrams',
    'sidebar.settings': 'Settings',
    'sidebar.about': 'About the System',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ru');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Загружаем сохраненный язык из localStorage
    const savedLanguage = localStorage.getItem('language') as Language | null;
    if (savedLanguage === 'ru' || savedLanguage === 'en') {
      setLanguageState(savedLanguage);
    } else {
      setLanguageState('ru');
    }
  }, []);

  useEffect(() => {
    if (!mounted) return;
    
    // Сохраняем в localStorage
    localStorage.setItem('language', language);
    
    // Отправляем событие для синхронизации между компонентами
    window.dispatchEvent(new CustomEvent('languagechange', { detail: language }));
  }, [language, mounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  if (!mounted) {
    return <>{children}</>;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Возвращаем значения по умолчанию для SSR, если контекст недоступен
    return {
      language: 'ru' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}
